// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAyhSxV8dggxE0uFUN3Pg3-fkblkz8zyc',
    appId: '1:97066810852:web:6d843757f16d1b95c8dbf1',
    messagingSenderId: '97066810852',
    projectId: 'student-management-ef5ab',
    authDomain: 'student-management-ef5ab.firebaseapp.com',
    storageBucket: 'student-management-ef5ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6tpYMuv7H2EIgoSXh-v_IDyAqsixcCA4',
    appId: '1:97066810852:android:11dd51ffa16431bdc8dbf1',
    messagingSenderId: '97066810852',
    projectId: 'student-management-ef5ab',
    storageBucket: 'student-management-ef5ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr8PNOYfoLEBFwOTGr2KE7NZ20yWztzTI',
    appId: '1:97066810852:ios:63406c05bfd6034ac8dbf1',
    messagingSenderId: '97066810852',
    projectId: 'student-management-ef5ab',
    storageBucket: 'student-management-ef5ab.appspot.com',
    iosBundleId: 'com.example.studentmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr8PNOYfoLEBFwOTGr2KE7NZ20yWztzTI',
    appId: '1:97066810852:ios:2a4e9ad9d032dfb1c8dbf1',
    messagingSenderId: '97066810852',
    projectId: 'student-management-ef5ab',
    storageBucket: 'student-management-ef5ab.appspot.com',
    iosBundleId: 'com.example.studentmanagement.RunnerTests',
  );
}
